FROM nvidia/cuda:11.8.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install basic tools and common dependencies, and install Python2 (without relying on python-pip from the repository)
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    lsb-release \
    build-essential \
    wget \
    curl \
    git \
    ffmpeg \
    libopenblas-dev \
    liblapack-dev \
    libjpeg-dev \
    libpng-dev \
    libx11-dev \
    libssl-dev \
    python2.7 \
    build-essential cmake ninja-build libomp5 \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/

# Install Node.js 20.x and vim
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs vim && \
    rm -rf /var/lib/apt/lists/

# Manually install pip for Python2python2
RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && \
    python2.7 get-pip.py && \
    rm get-pip.py

# Build and install Python 3.11 from source
RUN apt-get update && \
    apt-get install -y \
    libffi-dev \
    libsqlite3-dev \
    libbz2-dev \
    libreadline-dev \
    libncurses5-dev \
    libgdbm-dev \
    liblzma-dev \
    tk-dev \
    uuid-dev \
    zlib1g-dev && \
    cd /tmp && \
    wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz && \
    tar -xzf Python-3.11.9.tgz && \
    cd Python-3.11.9 && \
    ./configure --enable-optimizations --with-ensurepip=install && \
    make -j$(nproc) && \
    make altinstall && \
    ln -s /usr/local/bin/python3.11 /usr/bin/python3.11 && \
    ln -s /usr/local/bin/pip3.11 /usr/bin/pip3.11 && \
    cd / && \
    rm -rf /tmp/Python-3.11.9* && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip (for both Python2 and Python3.11)
RUN python2.7 -m pip install --upgrade pip
RUN python3.11 -m ensurepip && python3.11 -m pip install --upgrade pip

# Create two virtual environments
RUN python3.11 -m venv /opt/mol
RUN pip2 install virtualenv && virtualenv -p python2.7 /opt/adt

# Install pip dependencies in the mol environment
RUN /opt/mol/bin/pip install --upgrade pip && \
    /opt/mol/bin/pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118 && \
    /opt/mol/bin/pip install torch-scatter==2.1.2 torch-sparse==0.6.18 torch-spline-conv==1.2.2 torch-cluster==1.6.3 torch-geometric==2.4.0 \
    -f https://data.pyg.org/whl/torch-2.1.1+cu118.html

RUN /opt/mol/bin/pip install \
    aiohttp==3.11.4 aiosignal==1.3.1 async-timeout==4.0.3 \
    attrs==23.2.0 biopython==1.83 easydict==1.13 einops==0.7.0 fonttools==4.45.0 frozenlist==1.4.1 \
    fsspec==2024.3.1 joblib==1.4.0 lmdb==1.4.1 matplotlib==3.8.2 multidict==6.0.5 \
    psutil==5.9.8 scikit-learn==1.4.2 \
    threadpoolctl==3.4.0 tqdm==4.66.2 yarl==1.17.0 pyyaml==6.0.1 tensorboard==2.18.0 rdkit==2022.9.2 seaborn==0.13.2 \
    numpy==1.23.5 pandas==2.2.3 gymnasium==1.0.0

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libopenbabel-dev \
    openbabel \
    swig \
    python3-openbabel \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/lib/x86_64-linux-gnu/openbabel/* /usr/lib/ \
    && /opt/mol/bin/pip install openbabel-wheel

# Install pip dependencies in the adt environment (based on Python2)
RUN /opt/adt/bin/pip install --upgrade pip && \
    /opt/adt/bin/pip install setuptools==36.4.0 numpy==1.13.1

# Install AutoDockTools-Prepare (if source code or installation package is available)
RUN git clone https://github.com/jaimergp/autodocktools-prepare-py3k.git /tmp/autodocktools && \
    cd /tmp/autodocktools && /opt/adt/bin/python setup.py install && rm -rf /tmp/autodocktools

RUN wget -O /usr/local/bin/qvina2.1 https://github.com/QVina/qvina/raw/master/bin/qvina2.1 && \
    chmod +x /usr/local/bin/qvina2.1

# Set working directory
WORKDIR /workspace

RUN echo 'source /opt/mol/bin/activate' >> /root/.bashrc

CMD ["/bin/bash"]
