#!/bin/bash

# ============================================================================
# Grid Search for SPO Hyperparameters
# ============================================================================
# Search space:
#   - use_lipinski: true/false (2 options)
#   - w1 (SPM): 0, 0.25, 0.5, 0.75, 1.0 (5 levels)
#   - w2 (QED): 0.25, 0.5, 0.75, 1.0 (4 levels)
#   - w3 (SA):  0.25, 0.5, 0.75, 1.0 (4 levels)
#   - w4 (clash): 0.25, 0.5, 0.75, 1.0 (4 levels)
#
# Linearly independent combinations (no duplicates after normalization):
#   - Raw combinations: 5 * 4 * 4 * 4 = 320
#   - After removing linearly dependent ones: 294
#   - Total combinations: 2 * 294 = 588
#
# Usage:
#   ./grid_search_spo.sh                    # Normal run (50 proteins)
#   ./grid_search_spo.sh --smoke_test       # Smoke test (2 proteins)
#   ./grid_search_spo.sh --resume           # Resume from checkpoint
#   ./grid_search_spo.sh --smoke_test --resume
# ============================================================================

set -e

# ========== Parse command line arguments ==========
SMOKE_TEST=false
RESUME=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --smoke_test)
            SMOKE_TEST=true
            shift
            ;;
        --resume)
            RESUME=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--smoke_test] [--resume]"
            exit 1
            ;;
    esac
done

# ========== Configuration ==========
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Experiment directory
EXPERIMENT_NAME="grid_search_spo_$(date +%Y%m%d_%H%M%S)"
if [ "$SMOKE_TEST" = true ]; then
    EXPERIMENT_NAME="grid_search_spo_smoke_$(date +%Y%m%d_%H%M%S)"
fi

# If resuming, find the latest experiment directory
if [ "$RESUME" = true ]; then
    if [ "$SMOKE_TEST" = true ]; then
        LATEST_DIR=$(ls -td grid_search_spo_smoke_*/ 2>/dev/null | head -1)
    else
        LATEST_DIR=$(ls -td grid_search_spo_202*/ 2>/dev/null | grep -v smoke | head -1)
    fi

    if [ -n "$LATEST_DIR" ] && [ -d "$LATEST_DIR" ]; then
        EXPERIMENT_NAME="$LATEST_DIR"
        echo "Resuming from: $EXPERIMENT_NAME"
    else
        echo "No previous experiment found to resume. Starting fresh."
        RESUME=false
    fi
fi

EXPERIMENT_DIR="$SCRIPT_DIR/$EXPERIMENT_NAME"
mkdir -p "$EXPERIMENT_DIR"

# Log files
LOG_FILE="$EXPERIMENT_DIR/grid_search.log"
PROGRESS_FILE="$EXPERIMENT_DIR/progress.txt"
RESULTS_CSV="$EXPERIMENT_DIR/grid_search_results.csv"
COMPLETED_FILE="$EXPERIMENT_DIR/completed_tasks.txt"
TRAIN_SUBSET_FILE="$EXPERIMENT_DIR/train_subset_indices.txt"

# Model and data configuration
MODEL_CKPT="trained_models/500.pt"
SPM_CKPT="trained_models/spm_v4.pt"

# Sampling parameters
if [ "$SMOKE_TEST" = true ]; then
    NUM_PROTEINS=2
    NUM_SAMPLES=2
else
    NUM_PROTEINS=50
    NUM_SAMPLES=5
fi

SPO_INTERVAL=5
SPO_CANDIDATES=5
SPO_START_STEP=100
SAMPLING_TYPE="generalized"
CLASH_THRESHOLD=3.0

# GPU configuration
AVAILABLE_GPUS=(0 1)
MAX_TASKS_PER_GPU=2

# Hyperparameter grid
# Note: false comes first, prioritizing configurations without Lipinski filter
LIPINSKI_OPTIONS=("false" "true")
# Weight combinations will be generated by Python (linearly independent combinations)
WEIGHT_COMBINATIONS_FILE="$EXPERIMENT_DIR/weight_combinations.txt"

# ========== Logging functions ==========
log() {
    local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $1"
    echo "$msg" | tee -a "$LOG_FILE"
}

# ========== GPU task management ==========
declare -A GPU_TASKS  # GPU_TASKS[gpu_id]="pid1 pid2"
for gpu in "${AVAILABLE_GPUS[@]}"; do
    GPU_TASKS[$gpu]=""
done

get_gpu_running_count() {
    local gpu_id=$1
    local count=0
    local pids="${GPU_TASKS[$gpu_id]}"

    for pid in $pids; do
        if kill -0 "$pid" 2>/dev/null; then
            count=$((count + 1))
        fi
    done
    echo $count
}

cleanup_gpu_pids() {
    local gpu_id=$1
    local new_pids=""
    local pids="${GPU_TASKS[$gpu_id]}"

    for pid in $pids; do
        if kill -0 "$pid" 2>/dev/null; then
            new_pids="$new_pids $pid"
        fi
    done
    GPU_TASKS[$gpu_id]="$new_pids"
}

find_available_gpu() {
    while true; do
        for gpu in "${AVAILABLE_GPUS[@]}"; do
            cleanup_gpu_pids $gpu
            local count=$(get_gpu_running_count $gpu)
            if [ $count -lt $MAX_TASKS_PER_GPU ]; then
                echo $gpu
                return
            fi
        done
        sleep 10
    done
}

wait_all_tasks() {
    log "Waiting for all running tasks to complete..."
    while true; do
        local total=0
        for gpu in "${AVAILABLE_GPUS[@]}"; do
            cleanup_gpu_pids $gpu
            local count=$(get_gpu_running_count $gpu)
            total=$((total + count))
        done

        if [ $total -eq 0 ]; then
            break
        fi

        log "  Still running: $total tasks"
        sleep 30
    done
    log "All tasks completed."
}

# ========== Check if task is already completed ==========
is_task_completed() {
    local task_id=$1
    if [ -f "$COMPLETED_FILE" ]; then
        grep -q "^${task_id}$" "$COMPLETED_FILE" && return 0
    fi
    return 1
}

mark_task_completed() {
    local task_id=$1
    echo "$task_id" >> "$COMPLETED_FILE"
}

# ========== Generate task ID ==========
get_task_id() {
    local lipinski=$1
    local w_spm=$2
    local w_qed=$3
    local w_sa=$4
    local w_clash=$5
    echo "lip${lipinski}_spm${w_spm}_qed${w_qed}_sa${w_sa}_clash${w_clash}"
}

# ========== Main flow ==========
log "=============================================="
log "Grid Search for SPO Hyperparameters"
log "=============================================="
log "Experiment directory: $EXPERIMENT_DIR"
log "Smoke test: $SMOKE_TEST"
log "Resume: $RESUME"
log "Number of proteins: $NUM_PROTEINS"
log "Samples per protein: $NUM_SAMPLES"
log "GPUs: ${AVAILABLE_GPUS[*]}"
log "Max tasks per GPU: $MAX_TASKS_PER_GPU"
log "=============================================="

# ========== Step 1: Prepare training subset and weight combinations ==========
log ""
log "[Step 1] Preparing training subset and weight combinations..."

if [ "$RESUME" = true ] && [ -f "$TRAIN_SUBSET_FILE" ]; then
    log "Using existing training subset from $TRAIN_SUBSET_FILE"
else
    log "Sampling $NUM_PROTEINS proteins from training set..."
    python3 grid_search_helpers.py sample_train_subset \
        --num_proteins $NUM_PROTEINS \
        --output_file "$TRAIN_SUBSET_FILE" \
        --seed 42
    log "Training subset saved to $TRAIN_SUBSET_FILE"
fi

# Generate weight combinations (if not exists or not resuming)
if [ "$RESUME" = true ] && [ -f "$WEIGHT_COMBINATIONS_FILE" ]; then
    log "Using existing weight combinations from $WEIGHT_COMBINATIONS_FILE"
else
    log "Generating linearly independent weight combinations..."
    python3 grid_search_helpers.py generate_weight_combinations \
        --output_file "$WEIGHT_COMBINATIONS_FILE"
    log "Weight combinations saved to $WEIGHT_COMBINATIONS_FILE"
fi

NUM_WEIGHT_COMBOS=$(wc -l < "$WEIGHT_COMBINATIONS_FILE")
log "Total weight combinations: $NUM_WEIGHT_COMBOS"

# ========== Step 2: Initialize CSV file ==========
if [ ! -f "$RESULTS_CSV" ]; then
    log ""
    log "[Step 2] Initializing results CSV..."
    echo "task_id,use_lipinski,w_spm,w_qed,w_sa,w_clash,mean_qed,mean_sa,mean_logP,mean_lipinski,mean_mol_weight,diversity,collision_rate,brenk_rate,ring3_rate,ring4_rate,ring9plus_rate,cccc_range_rate,num_valid_samples,status" > "$RESULTS_CSV"
fi

# ========== Step 3: Generate all tasks ==========
log ""
log "[Step 3] Generating task list..."

TASK_LIST=()
TASK_COUNT=0
SKIP_COUNT=0

# Read from weight combinations file and combine with Lipinski options
for use_lip in "${LIPINSKI_OPTIONS[@]}"; do
    while IFS='|' read -r w_spm w_qed w_sa w_clash; do
        task_id=$(get_task_id $use_lip $w_spm $w_qed $w_sa $w_clash)

        if is_task_completed "$task_id"; then
            SKIP_COUNT=$((SKIP_COUNT + 1))
            continue
        fi

        TASK_LIST+=("$use_lip|$w_spm|$w_qed|$w_sa|$w_clash|$task_id")
        TASK_COUNT=$((TASK_COUNT + 1))
    done < "$WEIGHT_COMBINATIONS_FILE"
done

TOTAL_TASKS=$((TASK_COUNT + SKIP_COUNT))
log "Total tasks: $TOTAL_TASKS"
log "Already completed: $SKIP_COUNT"
log "Remaining tasks: $TASK_COUNT"

if [ $TASK_COUNT -eq 0 ]; then
    log "All tasks already completed!"
    log "Results saved in: $RESULTS_CSV"
    exit 0
fi

# ========== Step 4: Execute Grid Search ==========
log ""
log "[Step 4] Starting Grid Search..."

CURRENT_TASK=0

for task_info in "${TASK_LIST[@]}"; do
    IFS='|' read -r use_lip w_spm w_qed w_sa w_clash task_id <<< "$task_info"
    CURRENT_TASK=$((CURRENT_TASK + 1))

    log ""
    log "========== Task $CURRENT_TASK/$TASK_COUNT: $task_id =========="
    log "  use_lipinski: $use_lip"
    log "  w_spm: $w_spm, w_qed: $w_qed, w_sa: $w_sa, w_clash: $w_clash"

    # Find available GPU
    gpu_id=$(find_available_gpu)
    log "  Assigned to GPU: $gpu_id"

    # Create task directory
    TASK_DIR="$EXPERIMENT_DIR/tasks/$task_id"
    mkdir -p "$TASK_DIR"

    # Build sampling command
    LIPINSKI_FLAG=""
    if [ "$use_lip" = "true" ]; then
        LIPINSKI_FLAG="--use_lipinski"
    fi

    # Launch sampling and evaluation task
    (
        TASK_LOG="$TASK_DIR/task.log"

        echo "[$(date)] Starting task: $task_id" > "$TASK_LOG"
        echo "GPU: $gpu_id" >> "$TASK_LOG"
        echo "Parameters: lip=$use_lip, spm=$w_spm, qed=$w_qed, sa=$w_sa, clash=$w_clash" >> "$TASK_LOG"

        # Step 4a: Sampling
        echo "" >> "$TASK_LOG"
        echo "[$(date)] Running sampling..." >> "$TASK_LOG"

        python compare_spo_v2.py \
            --ckpt "$MODEL_CKPT" \
            --gpu "$gpu_id" \
            --train_subset_file "$TRAIN_SUBSET_FILE" \
            --num_samples $NUM_SAMPLES \
            --run_mode spo_only \
            --use_spm \
            --spm_checkpoint "$SPM_CKPT" \
            --spo_resample_interval $SPO_INTERVAL \
            --spo_num_candidates $SPO_CANDIDATES \
            --spo_start_step $SPO_START_STEP \
            --sampling_type $SAMPLING_TYPE \
            --score_weight_spm $w_spm \
            --score_weight_qed $w_qed \
            --score_weight_sa $w_sa \
            --score_weight_clash $w_clash \
            --clash_threshold $CLASH_THRESHOLD \
            --output_dir "$TASK_DIR" \
            $LIPINSKI_FLAG \
            >> "$TASK_LOG" 2>&1

        SAMPLE_STATUS=$?

        if [ $SAMPLE_STATUS -ne 0 ]; then
            echo "[$(date)] Sampling FAILED with status $SAMPLE_STATUS" >> "$TASK_LOG"
            echo "$task_id,$use_lip,$w_spm,$w_qed,$w_sa,$w_clash,,,,,,,,,,,,,0,SAMPLE_FAILED" >> "$RESULTS_CSV"
            exit 1
        fi

        # Find the generated pkl file
        PKL_FILE=$(find "$TASK_DIR" -name "spo_results.pkl" -o -name "samples_all.pkl" 2>/dev/null | head -1)

        if [ -z "$PKL_FILE" ] || [ ! -f "$PKL_FILE" ]; then
            echo "[$(date)] No pkl file found!" >> "$TASK_LOG"
            echo "$task_id,$use_lip,$w_spm,$w_qed,$w_sa,$w_clash,,,,,,,,,,,,,0,NO_PKL" >> "$RESULTS_CSV"
            exit 1
        fi

        echo "[$(date)] Found pkl file: $PKL_FILE" >> "$TASK_LOG"

        # Step 4b: Evaluation
        echo "" >> "$TASK_LOG"
        echo "[$(date)] Running evaluation..." >> "$TASK_LOG"

        EVAL_DIR="$TASK_DIR/eval_results"
        ./eval_all.sh "$PKL_FILE" --skip_vina "$EVAL_DIR" >> "$TASK_LOG" 2>&1

        EVAL_STATUS=$?

        if [ $EVAL_STATUS -ne 0 ]; then
            echo "[$(date)] Evaluation FAILED with status $EVAL_STATUS" >> "$TASK_LOG"
            echo "$task_id,$use_lip,$w_spm,$w_qed,$w_sa,$w_clash,,,,,,,,,,,,,0,EVAL_FAILED" >> "$RESULTS_CSV"
            exit 1
        fi

        # Step 4c: Parse results and write to CSV
        echo "" >> "$TASK_LOG"
        echo "[$(date)] Parsing results..." >> "$TASK_LOG"

        python3 grid_search_helpers.py parse_eval_results \
            --task_id "$task_id" \
            --use_lipinski "$use_lip" \
            --w_spm "$w_spm" \
            --w_qed "$w_qed" \
            --w_sa "$w_sa" \
            --w_clash "$w_clash" \
            --eval_dir "$EVAL_DIR" \
            --output_csv "$RESULTS_CSV" \
            >> "$TASK_LOG" 2>&1

        PARSE_STATUS=$?

        if [ $PARSE_STATUS -eq 0 ]; then
            echo "[$(date)] Task completed successfully!" >> "$TASK_LOG"
            echo "$task_id" >> "$COMPLETED_FILE"
        else
            echo "[$(date)] Result parsing FAILED" >> "$TASK_LOG"
        fi

    ) &

    # Record PID
    task_pid=$!
    GPU_TASKS[$gpu_id]="${GPU_TASKS[$gpu_id]} $task_pid"
    log "  Started with PID: $task_pid"

    # Brief wait to avoid launching too many tasks simultaneously
    sleep 3

    # Update progress
    echo "$CURRENT_TASK/$TASK_COUNT" > "$PROGRESS_FILE"
done

# ========== Step 5: Wait for all tasks to complete ==========
log ""
log "[Step 5] Waiting for all tasks to complete..."
wait_all_tasks

# ========== Step 6: Generate summary report ==========
log ""
log "[Step 6] Generating summary report..."

python3 grid_search_helpers.py generate_summary \
    --results_csv "$RESULTS_CSV" \
    --output_dir "$EXPERIMENT_DIR"

log ""
log "=============================================="
log "Grid Search Complete!"
log "=============================================="
log "Results CSV: $RESULTS_CSV"
log "Summary report: $EXPERIMENT_DIR/summary_report.txt"
log "Best configurations: $EXPERIMENT_DIR/best_configs.txt"
log "=============================================="
